export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_COATS = "GET_COATS";
export const GET_SNEAKERS = "GET_SNEAKERS";
export const GET_SHIRTS = "GET_SHIRTS";
export const GET_PANTS = "GET_PANTS";

export const FILTER_PRODUCTS_NEW = "FILTER_PRODUCTS_NEW";
export const FILTER_PRODUCTS_POPULAR = "FILTER_PRODUCTS_POPULAR";
export const FILTER_PRODUCTS_EXPENSIVE = "FILTER_PRODUCTS_EXPENSIVE";
export const FILTER_PRODUCTS_CHIP = "FILTER_PRODUCTS_CHIP";

export const FILTER_RESET = "FILTER_RESET";

export const IS_OPEN_CART = "IS_OPEN_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

